### ISSUE TITLE
Where is the index and so files located

### ISSUE THREAD

**Issue by Maxhem2** [davidfstr/Crystal-Web-Archiver#119]
Basically the title, where is the index file with all other assets? I only see database things

**Comment by davidfstr** [comment]
Not sure I understand your question. Are you asking about the format that Crystal uses to save downloaded URLs to disk?

**Comment by Maxhem2** [comment]
The normal structure, index.html and the other files and directorys, where are those located? I want a copy of the website for offline usage, so I dont always want to use Crystal to view it

**Comment by davidfstr** [comment]
Understood. Currently Crystal doesn't have the ability to export downloaded websites to regular files & folders, although this is a feature I'd like to add in the future. At the moment it's necessary to use a copy of Crystal to view a downloaded website.

The issue tracking the eventual addition of the Export feature is #41 . Consider subscribing to that feature so that you will be notified when it is being worked on & eventually completed.
